### ISSUE TITLE
net.cpp line 2013 errors out on startup

### ISSUE THREAD

**Issue by ghost** [ENikS/bitcoin-dev-msvc#1]
net.cpp line 2013 (CDataStream ssPeers(vchData, SER_DISK, CLIENT_VERSION);) fails with the following:

---
## Microsoft Visual C++ Runtime Library

Debug Assertion Failed!

Program: C:\bitcoin-dev-msvc\Win32\Debug\bin\bitcoind.exe
File: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\vector
Line: 72

Expression: vector iterator not dereferencable

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)

---

**Comment by ENikS** [comment]
Thank you, I will look into it. There are quite a few of these vector violations.

**Comment by ENikS** [comment]
This issue is fixed and could be closed
