### ISSUE TITLE
Synching With Bitcoin Core

### ISSUE THREAD

**Issue by abaziz** [ENikS/bitcoin-dev-msvc#2]
I'm interested in running the Bitcoin Core on VS2015. This repo looks like a great effort; I'm curious how the code from master Bitcoin Core project is synchronized into this repo? Does it have to be done manually? If so, what are the known risks, if any?

**Comment by ENikS** [comment]
At the moment it is not. It needs to be synced with master but I do not have time for it right now.

**Comment by abaziz** [comment]
Ok. Thanks for the quick response.
